markdown: redcarpet
name: Guide of Guides
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Province of British Columbia
  url: https://www.gov.bc.ca

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/bc_logo_transparent.png
logoalt: BC logo

repo_url: https://github.com/bcgov/guides-template

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:

- text: About This Repository
  internal: true
- text: About Citizens @ the Centre
  url: http://citizens-at-the-centre.pathfinder.bcgov
  internal: false
- text: Agile Scrum Guide
  url: http://agile-guide.pathfinder.bcgov/ag_alignwithagile/
  internal: false
- text: BC Agile Guides Template
  url: http://github-guide.pathfinder.bcgov/
  internal: false
- text: Data-Driven Decision Making
  url: http://data-driven-decision-making-guide.pathfinder.bcgov/
  internal: false
- text: Enterprise Business Architecture Guide
  url: http://eba-guide.pathfinder.bcgov/eba_context/eba_context_output/
  internal: false
- text: IT Product and Service Design Guide
  url: http://mode1-guide.pathfinder.bcgov/
  internal: false
- text: REST API Development Standard Guide
  url: http://api-guide.pathfinder.bcgov/
  internal: false
- text: Segmentation Guide
  url: http://segmentation-guide.pathfinder.bcgov/
  internal: false

repos:
- name: Guide of Guides
  description: Main repository
  url: https://github.com/bcgov/guide-of-guides

back_link:
  url: "http://guides.pathfinder.bcgov/"
  text: Read more BC Digital Guides

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "bc_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
